### ISSUE TITLE
[request] timer node -> send payload as well as topic

### ISSUE THREAD

**Issue by tampiss** [thingzi/thingzi-logic-timers#1]
Hi, any chance to extend the timer node to enable sending msg.payload as well as adding the option to send msg.topic? Best, M

**Comment by bryzix** [comment]
you can already do this if i understand you correctly. e.g. 

![image](https://user-images.githubusercontent.com/46371227/150013267-586d11e7-0196-45f8-9989-3c3157b3c2f6.png)

**Comment by bryzix** [comment]
if you want to send both at the same time, a better way is to use the change node e.g. 

![image](https://user-images.githubusercontent.com/46371227/150014542-13395c94-39d2-4dff-b972-943ecb412fd6.png)

much cleaner this way, particularly if you also want to have the case where payload is empty

**Comment by bryzix** [comment]
closing this as per comments above as its not something i think should be added
