### ISSUE TITLE
node-red crashes because of undefined variable tgtValue on Line 87:30 in schedule.js

### ISSUE THREAD

**Issue by DaKienes** [thingzi/thingzi-logic-timers#11]
[error] ReferenceError: tgtValue is not defined
    at Object.getValue (/home/.../.node-red/node_modules/thingzi-logic-timers/schedule.js:87:30)
    at Timeout.update [as _onTimeout] (/home/djk/.node-red/node_modules/thingzi-logic-timers/schedule.js:114:43)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

I replaced the variable "tgtValue" by "value" in 4 of following cases in my locals schedule.js and it works now.

       this.getValue = function(type, value) {
            switch (type) {
                case 'flow':
                    tgtValue = node.context().flow.get(value);
                    break;
                case 'global':
                    tgtValue = node.context().global.get(value);
                    break;
                case 'json':
                    tgtValue = JSON.parse(value);
                    break;
                case 'bool':
                    tgtValue = (value === "true");
                    break;
                case 'date':
                    value = (new Date()).getTime();
                    break;
                case 'num':
                    value = parseFloat(value);
                    break;
            }
            return value;

**Comment by bryzix** [comment]
thanks for this, ill get it sorted and release a new version

**Comment by bryzix** [comment]
fixed in version 1.2.3
