### ISSUE TITLE
Sheduler only sends a message, when value changes

### ISSUE THREAD

**Issue by DaKienes** [thingzi/thingzi-logic-timers#13]
I'm injecting a message into the sheduler and if the output value stays the same, it doesn't send a message.

In my solution I'm not allways using the schedule to switch the target object. I also use a manual mode to switch it on or off.
So: If I ask the scheduler the first time it will say ON and sends an output message,
Then I switch to manual mode and switch it to OFF.
Then I switch to scheduler mode and the scheduler says nothing changed since you asked me last time and doesn't send a message. The switch is now still OFF, but should be ON.

It seems to be efficient, to only send a message if the output changes. I think it's more logic (easier to understand) if it always sends a message. I can filter the messages in a second step, if I don't need them.

I tryed solving my issue, by overriding the sheduler by sending ON or OFF in the payload of the input message,

ON results in ON
OFF results in OFF
"" (empty string) results in OFF
INVALID resutlts in OFF
injecting a new msg-object without a payload variable results in OFF.
Everything else then ON seems to result in OFF

If I overrided it once by setting the payload I can't put the sheduler to its original mode.
The sheduler always shows a grey circle and OFF Status. Looks like I destroyed it. ;-)

Do you have an idea? Thx

**Comment by bryzix** [comment]
Current behaviour is by design but I can see your problem.  I'll have a think later today about this and what the options are.

**Comment by DaKienes** [comment]
I had a think about my task this morning. I'll use the sheduler to set a variable like flow.ShedulerStatus to true or false and use this variable in my logic of manual or automatic mode. It works fine now.

**Comment by bryzix** [comment]
ok, if you are unblocked for now thats great.  I'll consider adding an extra option for "always send" on the next update

**Comment by bryzix** [comment]
Hi, Ive added this option to the schedule node which should help you to simplify your setup and remove your workaround

<img width="473" alt="image" src="https://user-images.githubusercontent.com/46371227/168154237-8a144ca7-81a4-48a8-a557-9df58a7a14fc.png">
