### ISSUE TITLE
Add full msg to output

### ISSUE THREAD

**Issue by danielelopez1** [thingzi/thingzi-logic-timers#15]
Hello Team, it could be really nice if the node sent the complete output of msg instead of just one property.
For example, if I previously saved more than one object and I want to be able to recover them in the next node.
Obviously I can put them all in one and recover it later, but it would add unnecessary complexity to the flow.
It's just a suggestion, it's already a very good node :)

**Comment by bryzix** [comment]
Can you elaborate on this a bit more.  There are 3 nodes in this package...

- Timer - Doesn't accept an input
- Time Check - Passes the entire message as-is when the test succeeds (which sounds like what you are asking)
- Schedule - Accepts activation input, but the outputs are only send at schedule times

Always looking for good ideas so let me know...

**Comment by bryzix** [comment]
stale, i think i know what you mean, but id be keen if you know any examples of other nodes that have the behaviour you mention.
