### ISSUE TITLE
Issue with using both time and sun event

### ISSUE THREAD

**Issue by Dragonz423** [thingzi/thingzi-logic-timers#17]
When using a start time before midnight example 23:00 and then using a sun event example sunrise, the node will fail. if I use a time after 00:00 then it will properly work, if I use a time of 6:00 then it will also work properly. 

The use case is that my alarm arms at 23:00, and I have it check if it's disarmed for 20 minutes when it is then I tell it to arm and don't want it to do that action past sunrise.

**Comment by bryzix** [comment]
hi, been away for a few days.  Are you able to provide an example export of node red nodes showing this setup please?

**Comment by bryzix** [comment]
also which node type are you using for this?

**Comment by bryzix** [comment]
additional: ive tested the scenario you described with both the timer and time-check node and it seems to work fine.  If you share a reproduction of the issue here i can take a closer look at your specific setup.

**Comment by Dragonz423** [comment]
ok so its a issue also with home assistant itself, if you set the time of 23:00 then sunrise as the end, and the current time is past midnight 00:00 you will get a fail condition due to the automation checking the new day instead.

**Comment by bryzix** [comment]
so not an issue with the node?
