### ISSUE TITLE
Feature request Activity Node

### ISSUE THREAD

**Issue by vore** [thingzi/thingzi-logic-timers#18]
Hello!
I would like to use your Activity Node to control a light which is mainly controlled by a motion sensor. However there is also a manual switch which can turn off the light if wanted. I would need some kind of reset for this case to reset the timer. I would be fine with just a message.reset which will abort the timer inside the node and get ready for the next run.
I think we can agree about the amount of coffees :-)

Best regards
Volker

**Comment by bryzix** [comment]
Hi, just back from holiday so apologies for not replying sooner.  Let me have a think on that.  Coffee is always appreciated!

**Comment by bryzix** [comment]
Ive added a couple of features for resetting the timer in v1.4.4 which should cover most use cases...

- Support for a particular message received in the payload (leave blank if not required)
- Receiving a msg.reset as you suggested 

Let me know how you get on

![image](https://github.com/thingzi/thingzi-logic-timers/assets/46371227/b5de2cb5-f4e7-443d-afa1-966eb58c5426)

**Comment by vore** [comment]
Thank you!! I will go ahead with some testing now.
