### ISSUE TITLE
Check Time Schedule unchecked default to FALSE

### ISSUE THREAD

**Issue by anciltech** [thingzi/thingzi-logic-timers#2]
Currently, if a weekday is unchecked, the output defaults to a FALSE state (see screenshot). I falsely expected that his would default to true. 

If I uncheck a day, I would expect the time check to be OFF during that day, and let messages through. At the very least, this should be noted in the Node Properties IMO

<img width="852" alt="Screen Shot 2022-02-04 at 14 37 49" src="https://user-images.githubusercontent.com/79978026/152538339-d21f2556-9427-4045-b8ef-30b66cc7cbc9.png">

**Comment by bryzix** [comment]
The time check node forwards the exact message it receives without modification if the time range is valid.  Note that day selection is intended as part of the valid check range,  not when to apply the test.  If the check fails (out of range or the day is unchecked) the message will not be forwarded on the 1st output.  The node info says this...

![image](https://user-images.githubusercontent.com/46371227/152602752-17e911b1-01ed-473c-9b62-58f8e1e1be9e.png)

The 2nd output can be used to handle situations where the check failed.  

![image](https://user-images.githubusercontent.com/46371227/152602214-f7ee3135-62f4-4d90-bef6-164c16cfc130.png)

Is there a different behaviour you were looking for?

**Comment by bryzix** [comment]
Closing this now, i recently added a feature that may be what you are looking for...

![image](https://user-images.githubusercontent.com/46371227/153487356-1ecd26ee-8e94-408f-818b-f5dab0272009.png)

**Comment by anciltech** [comment]
Thanks! I appreciate you taking a look and implementing this change.
