### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by thobo123** [thingzi/thingzi-logic-timers#3]
I got an issue, withe the module thingzi-timer. In node red comes 'MODULE_NOT_FOUND' and in the log comes:
10 Feb 10:12:48 - [info]  - thingzi-logic-timers:thingzi-timer : Error: Cannot find module 'request'

I tried it in- and outside of Docker on an RPI 3.
![Bild_2022-02-10_140520](https://user-images.githubusercontent.com/58847998/153414079-ea161a2f-5616-438c-b249-bb5f0d90ab38.png)
![Bild_2022-02-10_140720](https://user-images.githubusercontent.com/58847998/153414414-55cafdee-d9f9-40ca-8232-215746306124.png)

**Comment by bryzix** [comment]
Hi, "request" was used in nodered and missing from the dependency list hence why this worked before.  As this library has been deprecated it was removed from newer versions of nodered causing this error.  Ive added it properly to the dependency list now to fix, but it should really be replaced. 

Version 1.1.9 should fix the issue

**Comment by thobo123** [comment]
That was quick!!

Thank you, for your realy good support!!

**Comment by bryzix** [comment]
no worries
