### ISSUE TITLE
Take on/off time from msg, flow, or global context

### ISSUE THREAD

**Issue by alfredopironti** [thingzi/thingzi-logic-timers#6]
Hi thingzi,

I'd love to use your nodes for home automations, in conjunction with Home Assistant (HA). To define on/off times from the HA UI, I use datetime inputs which, in node red, get exported as global context.

It would be super useful if your node could take on/off time not only as strings, but also resolving msg, flow or global context properties. Is this something you'd be willing to add?

Thanks for the great work already!

**Comment by bryzix** [comment]
Yeah, i think this is a good idea, ive done this on other nodes and its very useful.

**Comment by bryzix** [comment]
And just to check are we talking about the timer node here? schedule node is a bit more tricky for this :)

**Comment by alfredopironti** [comment]
Hi thingzi,

I was actually thinking of the time-check node :-) I would primarily use it to test whether the current (or given) time is within a range, with the range being defined via HA input datetime entities.

In the time-check GUI input, it would likely amount to allow the user to specify if the input is a direct time, or a reference to a context variable which contains a time.

(Timer and schedule nodes have somewhat more tightly coupled HA alternatives in the ha-websocket palette.)

Many thanks for the great work!

**Comment by bryzix** [comment]
For the value checked its currently possible to pass a timestamp via the "time" topic on the message to check against, which overrides the current time.  

from the node code (i think the docs suggested "timestamp" which is wrong , ill update that)
<img width="583" alt="image" src="https://user-images.githubusercontent.com/46371227/154585863-76ef684b-e96c-4f52-bd07-e21e60465fa4.png">

Currently there is no way to set the range values other than the UI as a simple string.  Id need to have a think about that though.

**Comment by alfredopironti** [comment]
I noticed the `msg.time` option, that's super-useful indeed! I'd have a comment there: you currently parse `msg.time` via `moment(msg.time)`, which means it must adhere to the momentjs expect time format. Crucially, that doesn't support the "HH:MM:SS" format which is accepted by the on/off events. In fact, would you consider using the `getEvent()` function to parse `msg.time`? `msg.time` could become an object containing the various fields (type, value, offset, random).

I'm happy to work on a pull request if you're positive about merging the proposed changes.

**Comment by bryzix** [comment]
It makes more sense at the data/message level for this to be based around timestamps as those are widely supported in node red and moment() can parse these. I added the string time as a simple user friendly-ish way to set the time from the Ux, mainly because i was learning at the time  & couldn't do a time control :)

I think the best solution is to use timestamps for time topic and any context read and keep the string for manual text entry. e.g.

![image](https://user-images.githubusercontent.com/46371227/154736989-c11f88c2-0dc3-4900-807b-0fa2f9e49979.png)

**Comment by bryzix** [comment]
actually, going to contradict myself now as thinking about it some more the range needs to work every day which doesnt work for a timestamp, so maybe for those cases it makes sense for using HH:MM:SS, the time topic still feels like its better served with a timestamp though

**Comment by alfredopironti** [comment]
Thanks for all your thoughts on the matter. My use case is probably a bit different, in that most of my input comes from HA, and it's hence in the form of HH:MM or HH:MM:SS (even the current time).

In general, if we could attach a "type" information to the time topic, that would probably give the required flexibility. In fact, since we're going to parse it with moment, we could accept a "format" parameter, that is then passed to the `moment(time,format)` constructor, so momentjs doesn't have to guess the format in the first place.

What do you think?

**Comment by bryzix** [comment]
ill take another look to see how easy that is

**Comment by alfredopironti** [comment]
Appreciated! I'm happy to support working on a patch with some guidance.

**Comment by bryzix** [comment]
see if you can run the branch 
https://github.com/thingzi/thingzi-logic-timers/tree/feature/node-check-improvements

and tell me what you think.  it may be closer to what you were thinking with some more general improvements all round

**Comment by bryzix** [comment]
im actually pretty happy with where this got to after some testing, so ive released the changes as v1.2.0.  Feel free to raise any PRs if you spot any issues or further improvements though.

**Comment by bryzix** [comment]
changes merged back into main now so that branch has gone, will close this discussion for now thanks.

**Comment by alfredopironti** [comment]
That's pretty awesome, thank you! As of now I only managed to view the code changes, and I think they're spot on; I also noticed that, while at it, you added the option to set on/off time via msg property, which I'm sure will be useful in other contexts.

I'm going to update my palette shortly; I'd share any PR if needed, but so many thanks for the hard and quick work!

**Comment by alfredopironti** [comment]
Closing the loop: I just used your updated node to replace all of the instances of a hacky-subflow I had to make, and it works like a charm! Many thanks again!
