### ISSUE TITLE
Multiple events if Randomise time within offset

### ISSUE THREAD

**Issue by schamu** [thingzi/thingzi-logic-timers#8]
If the offset is set to random, multiple events will be output.

**Comment by bryzix** [comment]
can you share a simple flow that demonstrates this please?

**Comment by schamu** [comment]
[{"id":"6a4f7888eec66620","type":"debug","z":"367b37491e0d1b31","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":2150,"y":380,"wires":[]},{"id":"aae490677b773785","type":"thingzi-timer","z":"367b37491e0d1b31","name":"","lat":"49.94","lon":"8.92","timerType":"trigger","startupMessage":false,"ontype":"tod","ontimesun":"dusk","ontimetod":"10:22","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"1","onoffset":"4","onrandomoffset":true,"offtype":"tod","offtimesun":"dawn","offtimetod":"","offpropertytype":"msg","offproperty":"payload","offvaluetype":"string","offvalue":"OFF","offoffset":"","offrandomoffset":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":1990,"y":380,"wires":[["6a4f7888eec66620"]]}]

**Comment by bryzix** [comment]
thats useful thanks.  It looks like when using the "trigger" option sometimes it will calculate the next event on the same day due to the random variation.  Should be an easy fix.

**Comment by bryzix** [comment]
fixed in 1.2.1
