### ISSUE TITLE
Offset larger then 60 minutes?

### ISSUE THREAD

**Issue by schamu** [thingzi/thingzi-logic-timers#9]
It would be good if you could specify a larger offset than 60 minutes, e.g. 300 minutes

**Comment by bryzix** [comment]
it is possible, but the offset does start to create complications around the on/off times if too large.  Out of interest is there a particular use case you are trying to handle that needs such a large amount o random variation?

**Comment by schamu** [comment]
I need it e.g. to lower the shutters 140 minutes after solar noon. But I don't need one for that
random offset but only a fixed offset.

**Comment by bryzix** [comment]
Ive upped this to 180 minutes in 1.2.1.  Let me know if that works for you.

**Comment by schamu** [comment]
Yes, thats is ok for me.

Thank you
